/*
 * auto generated by tools(注意:千万不要手动修改本文件)
 * avatarguide
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

[Serializable]
public class avatarguide : IBinarySerializable
{
	public int Id { get; set; }
	public string gender { get; set; }
	public string Top { get; set; }
	public string Bottom { get; set; }
	public string Necklace { get; set; }
	public string Gloves { get; set; }
	public string Ring { get; set; }
	public string EyeL { get; set; }
	public string EyeR { get; set; }
	public string Hair { get; set; }
	public string Head { get; set; }
	public string Socks { get; set; }
	public string Shoes { get; set; }
	public string Handbag { get; set; }
	public string Hat { get; set; }
	public string Glasses { get; set; }
	public string Watch { get; set; }
	public string Armletright { get; set; }
	public string Body { get; set; }
	public string Eyelash { get; set; }
	public string Earrings { get; set; }
	public string HeadColorId { get; set; }
	public string HairColorId { get; set; }
	public string EyelashColorId { get; set; }
	public string Blush { get; set; }
	public string Brow { get; set; }
	public string Eyeshadow { get; set; }
	public string Mouth { get; set; }
	public string Pupil { get; set; }
	public string PupilHPartColorId { get; set; }
	public string BlushHPartColorId { get; set; }
	public string BrowHPartColorId { get; set; }
	public string EyeshadowHPartColorId { get; set; }
	public string MouthHPartColorId { get; set; }
	public string FaceBSId { get; set; }
	public string FaceBSColorId { get; set; }
	public string EyeshapeBSId { get; set; }
	public string EyeshapeBSColorId { get; set; }
	public string NoseBSId { get; set; }
	public string NoseBSColorId { get; set; }
	public string MouthBSId { get; set; }
	public string MouthBSColorId { get; set; }

	public void DeSerialize(BinaryReader reader)
	{
		Id = reader.ReadInt32();
		gender = reader.ReadString();
		Top = reader.ReadString();
		Bottom = reader.ReadString();
		Necklace = reader.ReadString();
		Gloves = reader.ReadString();
		Ring = reader.ReadString();
		EyeL = reader.ReadString();
		EyeR = reader.ReadString();
		Hair = reader.ReadString();
		Head = reader.ReadString();
		Socks = reader.ReadString();
		Shoes = reader.ReadString();
		Handbag = reader.ReadString();
		Hat = reader.ReadString();
		Glasses = reader.ReadString();
		Watch = reader.ReadString();
		Armletright = reader.ReadString();
		Body = reader.ReadString();
		Eyelash = reader.ReadString();
		Earrings = reader.ReadString();
		HeadColorId = reader.ReadString();
		HairColorId = reader.ReadString();
		EyelashColorId = reader.ReadString();
		Blush = reader.ReadString();
		Brow = reader.ReadString();
		Eyeshadow = reader.ReadString();
		Mouth = reader.ReadString();
		Pupil = reader.ReadString();
		PupilHPartColorId = reader.ReadString();
		BlushHPartColorId = reader.ReadString();
		BrowHPartColorId = reader.ReadString();
		EyeshadowHPartColorId = reader.ReadString();
		MouthHPartColorId = reader.ReadString();
		FaceBSId = reader.ReadString();
		FaceBSColorId = reader.ReadString();
		EyeshapeBSId = reader.ReadString();
		EyeshapeBSColorId = reader.ReadString();
		NoseBSId = reader.ReadString();
		NoseBSColorId = reader.ReadString();
		MouthBSId = reader.ReadString();
		MouthBSColorId = reader.ReadString();
	}

	public void Serialize(BinaryWriter writer)
	{
		writer.Write(Id);
		writer.Write(gender);
		writer.Write(Top);
		writer.Write(Bottom);
		writer.Write(Necklace);
		writer.Write(Gloves);
		writer.Write(Ring);
		writer.Write(EyeL);
		writer.Write(EyeR);
		writer.Write(Hair);
		writer.Write(Head);
		writer.Write(Socks);
		writer.Write(Shoes);
		writer.Write(Handbag);
		writer.Write(Hat);
		writer.Write(Glasses);
		writer.Write(Watch);
		writer.Write(Armletright);
		writer.Write(Body);
		writer.Write(Eyelash);
		writer.Write(Earrings);
		writer.Write(HeadColorId);
		writer.Write(HairColorId);
		writer.Write(EyelashColorId);
		writer.Write(Blush);
		writer.Write(Brow);
		writer.Write(Eyeshadow);
		writer.Write(Mouth);
		writer.Write(Pupil);
		writer.Write(PupilHPartColorId);
		writer.Write(BlushHPartColorId);
		writer.Write(BrowHPartColorId);
		writer.Write(EyeshadowHPartColorId);
		writer.Write(MouthHPartColorId);
		writer.Write(FaceBSId);
		writer.Write(FaceBSColorId);
		writer.Write(EyeshapeBSId);
		writer.Write(EyeshapeBSColorId);
		writer.Write(NoseBSId);
		writer.Write(NoseBSColorId);
		writer.Write(MouthBSId);
		writer.Write(MouthBSColorId);
	}
}

[Serializable]
public partial class avatarguideConfig : IBinarySerializable
{
	public List<avatarguide> avatarguideInfos = new List<avatarguide>();
	public void DeSerialize(BinaryReader reader)
	{
		int count = reader.ReadInt32();
		for (int i = 0;i < count; i++)
		{
			avatarguide tempData = new avatarguide();
			tempData.DeSerialize(reader);
			avatarguideInfos.Add(tempData);
		}
	}

	public void Serialize(BinaryWriter writer)
	{
		writer.Write(avatarguideInfos.Count);
		for (int i = 0; i < avatarguideInfos.Count; i++)
		{
			avatarguideInfos[i].Serialize(writer);
		}
	}

	public IEnumerable<avatarguide> QueryById(int id)
	{
		var datas = from d in avatarguideInfos
					where d.Id == id
					select d;
		return datas;
	}
}
