/*
 * auto generated by tools(注意:千万不要手动修改本文件)
 * avatarkneadface
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Linq;

[Serializable]
public class avatarkneadface : IBinarySerializable
{
	public int Id { get; set; }
	public string Comment { get; set; }
	public int Type { get; set; }
	public int ItemId { get; set; }
	public int IsNeedWear { get; set; }
	public string ResPart { get; set; }
	public string ResName { get; set; }
	public string ColorCont { get; set; }
	public string ItemColor { get; set; }
	public string BSMin { get; set; }
	public string BSMax { get; set; }

	public void DeSerialize(BinaryReader reader)
	{
		Id = reader.ReadInt32();
		Comment = reader.ReadString();
		Type = reader.ReadInt32();
		ItemId = reader.ReadInt32();
		IsNeedWear = reader.ReadInt32();
		ResPart = reader.ReadString();
		ResName = reader.ReadString();
		ColorCont = reader.ReadString();
		ItemColor = reader.ReadString();
		BSMin = reader.ReadString();
		BSMax = reader.ReadString();
	}

	public void Serialize(BinaryWriter writer)
	{
		writer.Write(Id);
		writer.Write(Comment);
		writer.Write(Type);
		writer.Write(ItemId);
		writer.Write(IsNeedWear);
		writer.Write(ResPart);
		writer.Write(ResName);
		writer.Write(ColorCont);
		writer.Write(ItemColor);
		writer.Write(BSMin);
		writer.Write(BSMax);
	}
}

[Serializable]
public partial class avatarkneadfaceConfig : IBinarySerializable
{
	public List<avatarkneadface> avatarkneadfaceInfos = new List<avatarkneadface>();
	public void DeSerialize(BinaryReader reader)
	{
		int count = reader.ReadInt32();
		for (int i = 0;i < count; i++)
		{
			avatarkneadface tempData = new avatarkneadface();
			tempData.DeSerialize(reader);
			avatarkneadfaceInfos.Add(tempData);
		}
	}

	public void Serialize(BinaryWriter writer)
	{
		writer.Write(avatarkneadfaceInfos.Count);
		for (int i = 0; i < avatarkneadfaceInfos.Count; i++)
		{
			avatarkneadfaceInfos[i].Serialize(writer);
		}
	}

	public IEnumerable<avatarkneadface> QueryById(int id)
	{
		var datas = from d in avatarkneadfaceInfos
					where d.Id == id
					select d;
		return datas;
	}
}
